import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/addons/utils/SkeletonUtils.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const renderer=new THREE.WebGLRenderer({canvas:$('#game'),antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x0d1118); scene.fog=new THREE.Fog(0x0d1118,26,44);
const camera=new THREE.PerspectiveCamera(46,1,.1,100); camera.position.set(0,20,15.5); camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xeaf2ff,0x202534,2.1)); const sun=new THREE.DirectionalLight(0xffffff,2.2); sun.position.set(7,14,8); scene.add(sun);

const ADV='https://raw.githubusercontent.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0/main/addons/kaykit_character_pack_adventures/Characters/gltf/';
const SK='https://raw.githubusercontent.com/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0/main/addons/kaykit_character_pack_skeletons/Characters/gltf/';
const C={
 ranger:{n:'RANGER',hp:100,sp:4.8,cd:.22,dm:20,bs:13,col:0x35a7ff,super:'rapid',model:ADV+'Knight.glb'},
 crusher:{n:'CRUSHER',hp:135,sp:4,cd:.62,dm:13,bs:11.5,pel:5,spr:.26,col:0xff8a3d,super:'blast',model:ADV+'Barbarian.glb'},
 dash:{n:'DASH',hp:82,sp:6.2,cd:.17,dm:13,bs:14.5,col:0x9c6cff,super:'dash',model:ADV+'Rogue_Hooded.glb'},
 mage:{n:'MAGE',hp:88,sp:4.6,cd:.34,dm:24,bs:10.5,col:0x5be0d0,super:'nova',model:ADV+'Mage.glb'},
 rogue:{n:'ROGUE',hp:92,sp:5.7,cd:.19,dm:15,bs:14,col:0xffd45a,super:'fan',model:ADV+'Rogue.glb'},
 skeleton:{n:'BONES',hp:112,sp:4.35,cd:.42,dm:28,bs:11.8,col:0xded6c1,super:'storm',model:SK+'Skeleton_Warrior.glb'}
};
const A={hw:9.5,hh:6.2}; let arena=new THREE.Group(); scene.add(arena); let obs=[], bushes=[];
let select=['ranger','ranger'], arenaType='square', players=[], bullets=[], parts=[], running=false,time=90,last=performance.now(),hitStop=0;
const loader=new GLTFLoader(), cache=new Map();
const load=url=>cache.get(url)||cache.set(url,new Promise((ok,no)=>loader.load(url,ok,undefined,no))).get(url);

function clear(g){while(g.children.length){const x=g.children.pop();x.traverse?.(n=>{n.geometry?.dispose?.(); if(n.material&&!Array.isArray(n.material))n.material.dispose?.()})}}
function box(x,z,w,d,h=1.4,col=0x66758e,opt={}){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:col,roughness:.75}));m.position.set(x,h/2,z);arena.add(m);obs.push({x,z,hw:w/2,hd:d/2,m,hp:opt.hp||0,breakable:!!opt.hp})}
function cyl(x,z,r,h=1.5){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,18),new THREE.MeshStandardMaterial({color:0x71819a,roughness:.75}));m.position.set(x,h/2,z);arena.add(m);obs.push({x,z,r,circle:true,m})}
function bush(x,z,r=1.15){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x3f8c56,roughness:1,transparent:true,opacity:.8,depthWrite:false});for(let i=0;i<7;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(.42,.95,7),mat.clone()),a=i*Math.PI*2/7;m.position.set(Math.cos(a)*r*.4,.48,Math.sin(a)*r*.4);g.add(m)}g.position.set(x,0,z);arena.add(g);bushes.push({x,z,r})}
function build(t){clear(arena);obs=[];bushes=[];const f=new THREE.Mesh(new THREE.BoxGeometry(19,.5,12.4),new THREE.MeshStandardMaterial({color:0x39465a,roughness:.9}));f.position.y=-.3;arena.add(f);const grid=new THREE.GridHelper(20,20,0x8294b3,0x536078);grid.position.y=-.035;arena.add(grid);
 if(t==='square')[-3,3].forEach(x=>[-1.7,1.7].forEach(z=>box(x,z,1.4,1.4)));
 if(t==='pillars')[-3,3].forEach(x=>[-2,2].forEach(z=>cyl(x,z,.75)));
 if(t==='ring'){cyl(0,0,2,1.35);box(-6,0,1,3.4);box(6,0,1,3.4)}
 if(t==='cross'){box(0,0,1.15,4.5);box(0,0,4.5,1.15)}
 if(t==='hex')for(let i=0;i<6;i++){const a=i*Math.PI/3;cyl(Math.sin(a)*3.2,Math.cos(a)*3.2,.55)}
 if(t==='fort'){box(-3.8,2.2,3,.75);box(3.8,-2.2,3,.75);box(-5,1.2,.75,2.7);box(5,-1.2,.75,2.7);box(-1.5,0,.8,2);box(1.5,0,.8,2)}
 if(t==='bush'){box(-4.2,0,.8,2.7);box(4.2,0,.8,2.7);[[-2,-1.7],[2,1.7],[-2,1.7],[2,-1.7],[0,0]].forEach(v=>bush(...v))}
 if(t==='crates')[[-3,-1.8],[3,1.8],[3,-1.8],[-3,1.8],[0,0],[-6,0],[6,0]].forEach((v,i)=>box(v[0],v[1],1.15,1.15,1,0xb17b45,{hp:i===4?70:45}));
}
function blocked(pos,r=.58){if(Math.abs(pos.x)>A.hw-r||Math.abs(pos.z)>A.hh-r)return true;return obs.some(o=>o.circle?((pos.x-o.x)**2+(pos.z-o.z)**2<(o.r+r)**2):(Math.abs(pos.x-o.x)<o.hw+r&&Math.abs(pos.z-o.z)<o.hd+r))}
function hitObs(pos,r=.13){return obs.find(o=>o.circle?((pos.x-o.x)**2+(pos.z-o.z)**2<(o.r+r)**2):(Math.abs(pos.x-o.x)<o.hw+r&&Math.abs(pos.z-o.z)<o.hd+r))}

async function realModel(p){try{$('#asset-status').textContent='Loading CC0 3D characters…';const g=await load(p.cfg.model);if(!p.root.parent)return;const m=cloneSkeleton(g.scene);m.scale.setScalar(.72);m.rotation.y=Math.PI;m.position.y=.03;p.primitive.visible=false;p.host.add(m);p.mix=new THREE.AnimationMixer(m);const clips=g.animations,idle=clips.find(x=>x.name.toLowerCase().includes('idle'))||clips[0],walk=clips.find(x=>/walk|run/i.test(x.name));if(idle){p.idle=p.mix.clipAction(idle);p.idle.play()}if(walk){p.walk=p.mix.clipAction(walk);p.walk.play();p.walk.enabled=false}$('#asset-status').textContent='KayKit CC0 characters enabled'}catch(e){console.warn(e);$('#asset-status').textContent='3D model fallback active'}}
function player(i,key){const cfg=C[key],root=new THREE.Group(),primitive=new THREE.Group(),host=new THREE.Group();root.add(primitive,host);const shadow=new THREE.Mesh(new THREE.CircleGeometry(.72,20),new THREE.MeshBasicMaterial({color:0,transparent:true,opacity:.3,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.015;root.add(shadow);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.72,5,10),new THREE.MeshStandardMaterial({color:cfg.col}));body.position.y=.88;primitive.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.42,14,10),new THREE.MeshStandardMaterial({color:0xf1c6a5}));head.position.y=1.66;primitive.add(head);const gun=new THREE.Mesh(new THREE.BoxGeometry(.26,.24,key==='crusher'?1:1.25),new THREE.MeshStandardMaterial({color:0x202735,metalness:.25}));gun.position.set(0,1.05,-.62);root.add(gun);root.position.set(0,0,i?-4.5:4.5);scene.add(root);const p={i,key,cfg,root,primitive,host,hp:cfg.hp,max:cfg.hp,score:0,alive:true,inv:0,cd:0,sup:0,move:new THREE.Vector2(),aim:new THREE.Vector2(0,i?1:-1),r:.58,mix:null};realModel(p);return p}

let audio=null, realBgm=null;const bgm={normal:'./assets/audio/bgm/01_empacotatron_loop.ogg',sudden:'./assets/audio/bgm/02_trance_boss_battle.ogg',space:'./assets/audio/bgm/03_space_boss_battle.ogg'};
function ac(){return audio||(audio=new (window.AudioContext||window.webkitAudioContext)())}
function tone(f,d=.06,type='square',g=.025,slide=0){try{const c=ac(),o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.value=f;if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(40,f+slide),c.currentTime+d);v.gain.setValueAtTime(g,c.currentTime);v.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(v);v.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}}
function playBgm(mode='normal'){stopBgm();const a=new Audio(bgm[mode]||bgm.normal);a.loop=true;a.volume=.28;a.play().then(()=>realBgm=a).catch(()=>{});}
function stopBgm(){if(realBgm){realBgm.pause();realBgm=null}}
function burst(pos,col=0xffffff,n=10){for(let i=0;i<n;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.075,5,5),new THREE.MeshBasicMaterial({color:col,transparent:true}));m.position.copy(pos);scene.add(m);parts.push({m,v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*2.5,(Math.random()-.5)*4),life:.3})}}
function spawn(owner,dir,dm,sp){const p=players[owner],m=new THREE.Mesh(new THREE.SphereGeometry(.115,7,7),new THREE.MeshBasicMaterial({color:owner?0xff7b92:0x74d5ff}));m.position.copy(p.root.position).addScaledVector(dir,.95);m.position.y=.82;scene.add(m);bullets.push({m,v:dir.clone().multiplyScalar(sp),owner,life:1.45,dm})}
function shoot(i){const p=players[i];if(!running||!p?.alive||p.cd>0||p.aim.lengthSq()<.1)return;p.cd=p.cfg.cd;const base=new THREE.Vector3(p.aim.x,0,p.aim.y).normalize(),n=p.cfg.pel||1;for(let k=0;k<n;k++){const a=n===1?0:THREE.MathUtils.lerp(-p.cfg.spr,p.cfg.spr,k/(n-1));spawn(i,base.clone().applyAxisAngle(new THREE.Vector3(0,1,0),a),p.cfg.dm,p.cfg.bs)}tone(p.key==='crusher'?100:180,.05,'square',.02,60)}
function superMove(i){const p=players[i];if(!running||p.sup<100)return;p.sup=0;const dir=new THREE.Vector3(p.aim.x,0,p.aim.y).normalize();if(p.cfg.super==='rapid')for(let k=0;k<10;k++)setTimeout(()=>{p.cd=0;shoot(i)},k*75);if(p.cfg.super==='blast'||p.cfg.super==='nova'||p.cfg.super==='storm'){const n=p.cfg.super==='storm'?14:18;for(let k=0;k<n;k++){const a=k*Math.PI*2/n;spawn(i,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),18,10)}if(p.cfg.super==='nova')p.hp=Math.min(p.max,p.hp+20)}if(p.cfg.super==='dash'){for(let k=0;k<10;k++){const q=p.root.position.clone().addScaledVector(dir,.7);if(!blocked(q,p.r))p.root.position.copy(q)}p.inv=.45}if(p.cfg.super==='fan')for(let k=-4;k<=4;k++)spawn(i,dir.clone().applyAxisAngle(new THREE.Vector3(0,1,0),k*.12),19,14.5);tone(280,.12,'sine',.04,420);banner('SUPER!',450)}
function damage(v,dm,a){const p=players[v];if(!p.alive||p.inv>0)return;p.hp=Math.max(0,p.hp-dm);players[a].sup=Math.min(100,players[a].sup+dm*.9);p.sup=Math.min(100,p.sup+dm*.35);hitStop=.035;tone(85,.07,'sawtooth',.035,-30);burst(p.root.position.clone().setY(.9));if(navigator.vibrate)navigator.vibrate(18);if(p.hp<=0)ko(v,a)}
function ko(v,a){const p=players[v];p.alive=false;p.root.visible=false;players[a].score++;burst(p.root.position.clone().setY(.9),p.cfg.col,22);tone(150,.16,'sawtooth',.05,-100);banner('K.O!',700);hud();if(players[a].score>=3)setTimeout(()=>finish(a),700);else setTimeout(()=>reset(v),1000)}
function reset(i){const p=players[i];p.hp=p.max;p.alive=true;p.inv=1.15;p.root.visible=true;p.root.position.set(0,0,i?-4.5:4.5)}
function banner(t,ms=650){const b=$('#banner');b.textContent=t;b.classList.add('show');setTimeout(()=>b.classList.remove('show'),ms)}
function hud(){players.forEach((p,i)=>{$(`#p${i+1}-name`).textContent=p.cfg.n;$(`#p${i+1}-hp`).style.width=`${100*p.hp/p.max}%`;$(`#p${i+1}-super`).style.width=`${p.sup}%`;$(`#p${i+1}-score`).textContent=[0,1,2].map(n=>n<p.score?'●':'○').join(' ');$(`.super-btn[data-player="${i}"]`).classList.toggle('ready',p.sup>=100)})}
function finish(w){running=false;stopBgm();$('#winner').textContent=`P${w+1} WIN!`;$('#result-score').textContent=`${players[0].score} - ${players[1].score}`;$('#result').hidden=false}
function start(){players.forEach(p=>scene.remove(p.root));bullets.forEach(b=>scene.remove(b.m));parts.forEach(x=>scene.remove(x.m));bullets=[];parts=[];build(arenaType);players=[player(0,select[0]),player(1,select[1])];time=90;running=true;$('#menu').hidden=true;$('#hud').hidden=false;$('#controls').hidden=false;$('#result').hidden=true;playBgm(arenaType==='hex'?'space':'normal');hud();banner('FIGHT!',900)}

$$('.char-buttons').forEach(g=>g.onclick=e=>{const b=e.target.closest('button[data-char]');if(!b)return;const i=+g.dataset.player;select[i]=b.dataset.char;$$(`.char-buttons[data-player="${i}"] button`).forEach(x=>x.classList.toggle('selected',x===b))});
$('.arena-buttons').onclick=e=>{const b=e.target.closest('button[data-arena]');if(!b)return;arenaType=b.dataset.arena;$$('.arena-buttons button').forEach(x=>x.classList.toggle('selected',x===b))};
$('#start').onclick=()=>{ac().resume?.();start()};$('#rematch').onclick=start;$('#back-menu').onclick=()=>{running=false;stopBgm();$('#result').hidden=true;$('#hud').hidden=true;$('#controls').hidden=true;$('#menu').hidden=false};$$('.super-btn').forEach(b=>b.onpointerdown=e=>{e.preventDefault();superMove(+b.dataset.player)});

const ptr=new Map();$$('.stick-zone').forEach(z=>{const knob=z.querySelector('i'),base=z.querySelector('.stick'),pi=+z.dataset.player,kind=z.dataset.kind;const apply=e=>{if(!players[pi])return;const r=base.getBoundingClientRect();let dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);if(z.classList.contains('p2')){dx=-dx;dy=-dy}const max=r.width*.33,mag=Math.hypot(dx,dy);let x=dx/max,y=dy/max;if(mag>max){x*=max/mag;y*=max/mag}if(mag<max*.12)x=y=0;(kind==='move'?players[pi].move:players[pi].aim).set(x,y);knob.style.transform=`translate(calc(-50% + ${Math.max(-max,Math.min(max,dx))}px),calc(-50% + ${Math.max(-max,Math.min(max,dy))}px))`;if(kind==='aim'&&mag>max*.35)shoot(pi)};z.onpointerdown=e=>{e.preventDefault();z.setPointerCapture(e.pointerId);ptr.set(e.pointerId,1);apply(e)};z.onpointermove=e=>ptr.has(e.pointerId)&&apply(e);const end=e=>{ptr.delete(e.pointerId);knob.style.transform='translate(-50%,-50%)';if(players[pi]&&kind==='move')players[pi].move.set(0,0)};z.onpointerup=end;z.onpointercancel=end});

function update(dt){if(!running)return;time=Math.max(0,time-dt);if(time<=0){if(players[0].score!==players[1].score)finish(players[0].score>players[1].score?0:1);else{time=30;playBgm('sudden');banner('SUDDEN DEATH!',1000)}}players.forEach(p=>{p.cd=Math.max(0,p.cd-dt);p.inv=Math.max(0,p.inv-dt);if(!p.alive)return;const m=p.move.clone();if(m.lengthSq()>1)m.normalize();const q=p.root.position.clone();q.x+=m.x*p.cfg.sp*dt;q.z+=m.y*p.cfg.sp*dt;if(!blocked(q,p.r))p.root.position.copy(q);if(p.aim.lengthSq()>.1)p.root.rotation.y=Math.atan2(p.aim.x,p.aim.y)+Math.PI;if(p.mix){const moving=p.move.lengthSq()>.08;if(p.walk){p.walk.enabled=moving;p.walk.setEffectiveWeight(moving?1:0)}if(p.idle){p.idle.enabled=!moving;p.idle.setEffectiveWeight(moving?0:1)}p.mix.update(dt)}p.root.visible=p.inv>0?Math.floor(p.inv*12)%2===0:true});for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.life-=dt;b.m.position.addScaledVector(b.v,dt);let rm=b.life<=0;const o=!rm&&hitObs(b.m.position);if(o){if(o.breakable){o.hp-=b.dm;burst(b.m.position.clone(),0xd6a05d,6);if(o.hp<=0){arena.remove(o.m);obs=obs.filter(x=>x!==o);burst(b.m.position.clone(),0xc58b4a,16)}}rm=true}else if(!rm&&(Math.abs(b.m.position.x)>A.hw||Math.abs(b.m.position.z)>A.hh))rm=true;if(!rm){const e=players[1-b.owner];if(e.alive&&b.m.position.distanceToSquared(e.root.position)<.52)damage(1-b.owner,b.dm,b.owner),rm=true}if(rm){scene.remove(b.m);bullets.splice(i,1)}}for(let i=parts.length-1;i>=0;i--){const x=parts[i];x.life-=dt;x.m.position.addScaledVector(x.v,dt);x.v.y-=6*dt;x.m.material.opacity=Math.max(0,x.life/.3);if(x.life<=0){scene.remove(x.m);parts.splice(i,1)}}hud();$('#timer').textContent=Math.ceil(time)}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(hitStop>0)hitStop-=dt;else update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}build('square');requestAnimationFrame(loop);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
